//HintName: TestQ2.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace GenericsGenerationTest;

public class TestQ2 : StatelessQueryHandler<ITestManagerGrain, GenericsGenerationTest.TestState>
{
    public override async Task<GenericsGenerationTest.TestState> Execute()
    {
        return await QueryFactory.GetChild<GenericsGenerationTest.TestState>()
            .Ask<TestQuery2Type<GenericsGenerationTest.TestState, GenericsGenerationTest.TestState>, GenericsGenerationTest.TestState>()
            .Run(GetPrimaryKeyString());
    }
}

public static class ITestManagerGrainTestQ2Extensions
{
        public static IGrainQueryBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>, GenericsGenerationTest.TestState> TestQ2(this IGrainQueryBaseBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>> builder)
        {
            return builder.Ask<TestQ2, GenericsGenerationTest.TestState>();
        }

        public static IGrainCommandBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<GenericsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>, GenericsGenerationTest.TestState> TestQ2(this IGrainCommandBaseBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<GenericsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>> builder)
        {
            return builder.Ask<TestQ2, GenericsGenerationTest.TestState>();
        }

        public static IGrainQueryBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>, GenericsGenerationTest.TestState> TestQ2<T>(this IGrainQueryBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>, T> builder)
        {
            return builder.Ask<TestQ2, GenericsGenerationTest.TestState>();
        }

        public static IGrainCommandBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<GenericsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>, GenericsGenerationTest.TestState> TestQ2<T>(this IGrainCommandBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<GenericsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>, T> builder)
        {
            return builder.Ask<TestQ2, GenericsGenerationTest.TestState>();
        }
}
