//HintName: TestC2.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace GenericsGenerationTest;

public class TestC2 : RootCommandHandler<ITestAggregate, double>
{
    public override async Task<double> Execute()
    {
        return await CommandFactory.GetEntity<GenericsGenerationTest.TestState>()
            .Tell<TestCommand2Type<GenericsGenerationTest.TestState, double>, double>()
            .Run(GetRootKeyString());
    }
}

public static class ITestAggregateTestC2Extensions
{
        public static IGrainCommandBuilder<GenericsGenerationTest.ITestAggregate, BaseRootCommandHandler<GenericsGenerationTest.ITestAggregate>, BaseRootQueryHandler<GenericsGenerationTest.ITestAggregate>, double> TestC2(this IGrainCommandBaseBuilder<GenericsGenerationTest.ITestAggregate, BaseRootCommandHandler<GenericsGenerationTest.ITestAggregate>, BaseRootQueryHandler<GenericsGenerationTest.ITestAggregate>> builder)
        {
            return builder.Tell<TestC2, double>();
        }

        public static IGrainCommandBuilder<GenericsGenerationTest.ITestAggregate, BaseRootCommandHandler<GenericsGenerationTest.ITestAggregate>, BaseRootQueryHandler<GenericsGenerationTest.ITestAggregate>, double> TestC2<T>(this IGrainCommandBuilder<GenericsGenerationTest.ITestAggregate, BaseRootCommandHandler<GenericsGenerationTest.ITestAggregate>, BaseRootQueryHandler<GenericsGenerationTest.ITestAggregate>, T> builder)
        {
            return builder.Tell<TestC2, double>();
        }
}
