//HintName: TestC1.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace GenericsGenerationTest;

public class TestC1 : StatelessCommandHandler<ITestManagerGrain>
{
    public override async Task Execute()
    {
        await CommandFactory.GetChild<GenericsGenerationTest.TestState>()
            .Tell<TestCommand1Type<GenericsGenerationTest.TestState>>()
            .Run(GetPrimaryKeyString());
    }
}

public static class ITestManagerGrainTestC1Extensions
{
        public static IGrainCommandBaseBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<GenericsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>> TestC1(this IGrainCommandBaseBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<GenericsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>> builder)
        {
            return builder.Tell<TestC1>();
        }

        public static IGrainCommandBaseBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<GenericsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>> TestC1<T>(this IGrainCommandBuilder<GenericsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<GenericsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<GenericsGenerationTest.ITestManagerGrain>, T> builder)
        {
            return builder.Tell<TestC1>();
        }
}
