//HintName: TestQ2.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace SimpleCommandsAndQueriesTest;

public class TestQ2 : StatelessQueryHandler<ITestManagerGrain, double>
{
    public override async Task<double> Execute()
    {
        return await QueryFactory.GetChild<SimpleCommandsAndQueriesTest.TestState>()
            .Ask<TestQuery2Type, double>()
            .Run(GetPrimaryKeyString());
    }
}

public static class ITestManagerGrainTestQ2Extensions
{
        public static IGrainQueryBuilder<SimpleCommandsAndQueriesTest.ITestManagerGrain, BaseStatelessQueryHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, double> TestQ2(this IGrainQueryBaseBuilder<SimpleCommandsAndQueriesTest.ITestManagerGrain, BaseStatelessQueryHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>> builder)
        {
            return builder.Ask<TestQ2, double>();
        }

        public static IGrainQueryBuilder<SimpleCommandsAndQueriesTest.ITestManagerGrain, BaseStatelessQueryHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, double> TestQ2<T>(this IGrainQueryBuilder<SimpleCommandsAndQueriesTest.ITestManagerGrain, BaseStatelessQueryHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, T> builder)
        {
            return builder.Ask<TestQ2, double>();
        }

        public static IGrainCommandBuilder<SimpleCommandsAndQueriesTest.ITestManagerGrain, BaseStatelessCommandHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, BaseStatelessQueryHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, double> TestQ2(this IGrainCommandBaseBuilder<SimpleCommandsAndQueriesTest.ITestManagerGrain, BaseStatelessCommandHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, BaseStatelessQueryHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>> builder)
        {
            return builder.Ask<TestQ2, double>();
        }

        public static IGrainCommandBuilder<SimpleCommandsAndQueriesTest.ITestManagerGrain, BaseStatelessCommandHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, BaseStatelessQueryHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, double> TestQ2<T>(this IGrainCommandBuilder<SimpleCommandsAndQueriesTest.ITestManagerGrain, BaseStatelessCommandHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, BaseStatelessQueryHandler<SimpleCommandsAndQueriesTest.ITestManagerGrain>, T> builder)
        {
            return builder.Ask<TestQ2, double>();
        }
}
