//HintName: TestQ2.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace SimpleCommandsAndQueriesTest;

public class TestQ2 : RootQueryHandler<ITestAggregate, double>
{
    public override async Task<double> Execute()
    {
        return await QueryFactory.GetEntity<SimpleCommandsAndQueriesTest.TestState>()
            .Ask<TestQuery2Type, double>()
            .Run(GetRootKeyString());
    }
}

public static class ITestAggregateTestQ2Extensions
{
        public static IGrainQueryBuilder<SimpleCommandsAndQueriesTest.ITestAggregate, BaseRootQueryHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, double> TestQ2(this IGrainQueryBaseBuilder<SimpleCommandsAndQueriesTest.ITestAggregate, BaseRootQueryHandler<SimpleCommandsAndQueriesTest.ITestAggregate>> builder)
        {
            return builder.Ask<TestQ2, double>();
        }

        public static IGrainQueryBuilder<SimpleCommandsAndQueriesTest.ITestAggregate, BaseRootQueryHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, double> TestQ2<T>(this IGrainQueryBuilder<SimpleCommandsAndQueriesTest.ITestAggregate, BaseRootQueryHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, T> builder)
        {
            return builder.Ask<TestQ2, double>();
        }

        public static IGrainCommandBuilder<SimpleCommandsAndQueriesTest.ITestAggregate, BaseRootCommandHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, BaseRootQueryHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, double> TestQ2(this IGrainCommandBaseBuilder<SimpleCommandsAndQueriesTest.ITestAggregate, BaseRootCommandHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, BaseRootQueryHandler<SimpleCommandsAndQueriesTest.ITestAggregate>> builder)
        {
            return builder.Ask<TestQ2, double>();
        }

        public static IGrainCommandBuilder<SimpleCommandsAndQueriesTest.ITestAggregate, BaseRootCommandHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, BaseRootQueryHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, double> TestQ2<T>(this IGrainCommandBuilder<SimpleCommandsAndQueriesTest.ITestAggregate, BaseRootCommandHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, BaseRootQueryHandler<SimpleCommandsAndQueriesTest.ITestAggregate>, T> builder)
        {
            return builder.Ask<TestQ2, double>();
        }
}
