//HintName: TestC3.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace CommandsAndQueriesWithObjectsGenerationTest;

public class TestC3 : StatelessCommandHandler<ITestManagerGrain, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, double>
{
    public override async Task<double> Execute(CommandsAndQueriesWithObjectsGenerationTest.TestInputObject input)
    {
        return await CommandFactory.GetChild<CommandsAndQueriesWithObjectsGenerationTest.TestState>()
            .Tell<TestCommand3Type, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, double>(input)
            .Run(GetPrimaryKeyString());
    }
}

public static class ITestManagerGrainTestC3Extensions
{
        public static IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, double> TestC3(this IGrainCommandBaseBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>> builder, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject input)
        {
            return builder.Tell<TestC3, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, double>(input);
        }

        public static IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, double> TestC3<T>(this IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, T> builder, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject input)
        {
            return builder.Tell<TestC3, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, double>(input);
        }

        public static IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, double> ThenTestC3(this IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject> builder)
        {
            return builder.ThenTell<TestC3, double>();
        }
}
