//HintName: TestQ3.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace CommandsAndQueriesWithObjectsGenerationTest;

public class TestQ3 : StatelessQueryHandler<ITestManagerGrain, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject>
{
    public override async Task<CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject> Execute(CommandsAndQueriesWithObjectsGenerationTest.TestInputObject input)
    {
        return await QueryFactory.GetChild<CommandsAndQueriesWithObjectsGenerationTest.TestState>()
            .Ask<TestQuery3Type, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject>(input)
            .Run(GetPrimaryKeyString());
    }
}

public static class ITestManagerGrainTestQ3Extensions
{
        public static IGrainQueryBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject> TestQ3(this IGrainQueryBaseBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>> builder, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject input)
        {
            return builder.Ask<TestQ3, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject>(input);
        }

        public static IGrainQueryBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject> TestQ3<T>(this IGrainQueryBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, T> builder, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject input)
        {
            return builder.Ask<TestQ3, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject>(input);
        }

        public static IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject> TestQ3(this IGrainCommandBaseBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>> builder, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject input)
        {
            return builder.Ask<TestQ3, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject>(input);
        }

        public static IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject> TestQ3<T>(this IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, T> builder, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject input)
        {
            return builder.Ask<TestQ3, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject>(input);
        }

        public static IGrainQueryBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject> ThenTestQ3(this IGrainQueryBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject> builder)
        {
            return builder.ThenAsk<TestQ3, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject>();
        }

        public static IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject> ThenTestQ3(this IGrainCommandBuilder<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<CommandsAndQueriesWithObjectsGenerationTest.ITestManagerGrain>, CommandsAndQueriesWithObjectsGenerationTest.TestInputObject> builder)
        {
            return builder.ThenAsk<TestQ3, CommandsAndQueriesWithObjectsGenerationTest.TestOutputObject>();
        }
}
