//HintName: TestC3.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace KeyStrategiesGenerationTest;

public class TestC3 : StatelessCommandHandler<ITestAggregate, KeyStrategiesGenerationTest.TestInputObject, double>
{
    public override async Task<double> Execute(KeyStrategiesGenerationTest.TestInputObject input)
    {
        return await CommandFactory.GetEntity<KeyStrategiesGenerationTest.TestState>()
            .Tell<TestCommand3Type, KeyStrategiesGenerationTest.TestInputObject, double>(input)
            .Run(KeyStrategiesGenerationTest.ITestAggregate.SetValue3TypeKey(input));
    }
}

public static class ITestAggregateTestC3Extensions
{
        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestC3(this IGrainCommandBaseBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>> builder, KeyStrategiesGenerationTest.TestInputObject input)
        {
            return builder.Tell<TestC3, KeyStrategiesGenerationTest.TestInputObject, double>(input);
        }

        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestC3<T>(this IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, T> builder, KeyStrategiesGenerationTest.TestInputObject input)
        {
            return builder.Tell<TestC3, KeyStrategiesGenerationTest.TestInputObject, double>(input);
        }

        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> ThenTestC3(this IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, KeyStrategiesGenerationTest.TestInputObject> builder)
        {
            return builder.ThenTell<TestC3, double>();
        }
}
