//HintName: TestQ3.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace KeyStrategiesGenerationTest;

public class TestQ3 : RootQueryHandler<ITestAggregate, double, double>
{
    public override async Task<double> Execute(double input)
    {
        return await QueryFactory.GetEntity<KeyStrategiesGenerationTest.TestState>()
            .Ask<TestQuery3Type, double, double>(input)
            .Run("testKey2");
    }
}

public static class ITestAggregateTestQ3Extensions
{
        public static IGrainQueryBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestQ3(this IGrainQueryBaseBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>> builder, double input)
        {
            return builder.Ask<TestQ3, double, double>(input);
        }

        public static IGrainQueryBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestQ3<T>(this IGrainQueryBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, T> builder, double input)
        {
            return builder.Ask<TestQ3, double, double>(input);
        }

        public static IGrainQueryBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> ThenTestQ3(this IGrainQueryBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> builder)
        {
            return builder.ThenAsk<TestQ3, double>();
        }

        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestQ3(this IGrainCommandBaseBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>> builder, double input)
        {
            return builder.Ask<TestQ3, double, double>(input);
        }

        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestQ3<T>(this IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, T> builder, double input)
        {
            return builder.Ask<TestQ3, double, double>(input);
        }

        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> ThenTestQ3(this IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> builder)
        {
            return builder.ThenAsk<TestQ3, double>();
        }
}
