//HintName: TestQ2.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace KeyStrategiesGenerationTest;

public class TestQ2 : RootQueryHandler<ITestAggregate, double>
{
    public override async Task<double> Execute()
    {
        return await QueryFactory.GetEntity<KeyStrategiesGenerationTest.TestState>()
            .Ask<TestQuery2Type, double>()
            .Run(KeyStrategiesGenerationTest.ITestAggregate.SetValue2TypeKey());
    }
}

public static class ITestAggregateTestQ2Extensions
{
        public static IGrainQueryBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestQ2(this IGrainQueryBaseBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>> builder)
        {
            return builder.Ask<TestQ2, double>();
        }

        public static IGrainQueryBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestQ2<T>(this IGrainQueryBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, T> builder)
        {
            return builder.Ask<TestQ2, double>();
        }

        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestQ2(this IGrainCommandBaseBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>> builder)
        {
            return builder.Ask<TestQ2, double>();
        }

        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, double> TestQ2<T>(this IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestAggregate, BaseRootCommandHandler<KeyStrategiesGenerationTest.ITestAggregate>, BaseRootQueryHandler<KeyStrategiesGenerationTest.ITestAggregate>, T> builder)
        {
            return builder.Ask<TestQ2, double>();
        }
}
