//HintName: TestC3.g.cs
// This file was generated by the Remotr.SourceGen HandlerAttributeGenerator.

using System;
using System.Threading.Tasks;
using Remotr;

namespace KeyStrategiesGenerationTest;

public class TestC3 : StatelessCommandHandler<ITestManagerGrain, KeyStrategiesGenerationTest.TestInputObject, double>
{
    public override async Task<double> Execute(KeyStrategiesGenerationTest.TestInputObject input)
    {
        return await CommandFactory.GetChild<KeyStrategiesGenerationTest.TestState>()
            .Tell<TestCommand3Type, KeyStrategiesGenerationTest.TestInputObject, double>(input)
            .Run(KeyStrategiesGenerationTest.ITestManagerGrain.SetValue3TypeKey(input));
    }
}

public static class ITestManagerGrainTestC3Extensions
{
        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, double> TestC3(this IGrainCommandBaseBuilder<KeyStrategiesGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestManagerGrain>> builder, KeyStrategiesGenerationTest.TestInputObject input)
        {
            return builder.Tell<TestC3, KeyStrategiesGenerationTest.TestInputObject, double>(input);
        }

        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, double> TestC3<T>(this IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, T> builder, KeyStrategiesGenerationTest.TestInputObject input)
        {
            return builder.Tell<TestC3, KeyStrategiesGenerationTest.TestInputObject, double>(input);
        }

        public static IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, double> ThenTestC3(this IGrainCommandBuilder<KeyStrategiesGenerationTest.ITestManagerGrain, BaseStatelessCommandHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, BaseStatelessQueryHandler<KeyStrategiesGenerationTest.ITestManagerGrain>, KeyStrategiesGenerationTest.TestInputObject> builder)
        {
            return builder.ThenTell<TestC3, double>();
        }
}
